### ISSUE TITLE
Suggestion list in hfst-ospell-office not unique

### ISSUE THREAD

**Issue by snomos** [hfst/hfst-ospell#37] opened 2017-11-27 15:27 UTC
Consider the following (the two first suggestions):

```
echo '8	Jupmelistie' | hfst-ospell-office sma.zhfst
@@ hfst-ospell-office is alive
&	Jupmielistie	Jupmielistie	Jupmielijstie	Jupmielisnie	Hopmelistie	Bupmemistie	Ruppelistie	Juelistie
```

The reason is that there is an underlying difference in initial case:

```
echo 'Jupmelistie' | hfst-ospell -S build/spellers/tools/spellcheckers/fstbased/desktop/hfst/sma.zhfst
"Jupmelistie" is NOT in the lexicon:
Corrections for "Jupmelistie":
Jupmielistie    12.647461
jupmielistie    23.495081
Jupmielijstie    24.495081
Jupmielisnie    24.495081
hopmelistie    32.495079
bupmemistie    33.495079
Ruppelistie    33.495079
Juelistie    33.495079
Jupmelevistie    45.495079
```

Newest hfst-ospell, newest macOS, newest XCode:

hfst-ospell: 1d088e1727aa3ad0e5d4616536692ae3e5c4fda2
macOS: 10.13.1 (17B48)
XCode: 9.1 (9B55)

**Comment by TinoDidriksen** [comment] 2017-11-27 15:31
That is by design. The output casing is massaged to match the input casing:
- https://github.com/hfst/hfst-ospell/blob/master/office.cc#L131
- https://github.com/hfst/hfst-ospell/blob/master/office.cc#L92

**Comment by snomos** [comment] 2017-11-27 15:37
True, and agreed, but after case massaging the suggestions still need to be made unique, with the best/lowest-weight suggestion being the one surviving. Otherwise users will be a bit confused.

**Comment by TinoDidriksen** [comment] 2017-11-27 16:13
Fixed in a4aeae077d59160fb070b2d57b324bea5600ad67

**Comment by snomos** [comment] 2017-11-27 19:11
File to reproduce crashing issue:
[speller_input.to.txt](https://github.com/hfst/hfst-ospell/files/1507232/speller_input.to.txt)

**Comment by snomos** [comment] 2017-11-27 19:13
With the attached file, this is what happens to me:

```
$ hfst-ospell-office build/spellers/tools/spellcheckers/fstbased/desktop/hfst/sma.zhfst < devtools/speller_input.to.txt 
@@ hfst-ospell-office is alive
&	Divvun speller for Southern Sami	sma version 4.1, 27.11.2017, rev160499	Built using HFST 3.13.0
&	mænngan	mangan	Anngan	Inngan	Unngan	jånngan	mahgan	lingan	majgan	mannegan
&	ryöknemebuerkiestimmine	ryöknemeboerkestimmine	ryöknemebeerkestimmine	ryökneme-buerkiestimmine	ryöknege-buerkiestimmine	ryökneme-berkiestimmine	ryökneme-boerkestimmine	ryökneme-buerkiestimmide	ryökneme-buerkiestimmie	ryökneme-buerkiestimmige
*
&	tjaalegeåahpetjh	tjaalegeåahpetji	tjaalegeåahpetje	tjaalehåahpetje	tjaalegeååhpetjh	tjaalegeååhpetji	tjaalegeråhpetje	tjaalehååhpetjh	tjaalehååhpetji	tjaaleseåahpetje
&	Aarportesne	Aalborgesne	Harborgesne	Aarporteste	Garborgesne	Airportesne	Aarportese	Aarportene
&	nuelien	nuelesne	vuelelen	buelele	neeleli	noelen	buelelh	neelelin	neelele	neelen
&	njealjehts	njealjehtsh	njealjehtsi	bieljehts	njieljeste	nielehts	jielijehts	njaelkehts	njoenjehts	njoelehts
&	edtjagan	edtjigan	edtjhgan	eatjagan	adtjagan	edtjijægan	idtjigan	eatjhgan	edtjingan	ïedtjegan
&	deanere	deanerh	deaneri	deavere	deanerem	deaneren	dievere	dïenesje	dïeneste	dïehre
hfst-ospell-office(5786,0x7fffaecbd340) malloc: *** error for object 0x6000000000000035: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
&	Jupmielistie		Jupmielijstie	Jupmielisnie	Hopmelistie	Bupmemistie	Ruppelistie	Juelistie	Jupmelevistie																		Abort trap: 6
```

**Closed** 2017-12-01 22:32 UTC
